# Generated by Django 4.0 on 2022-01-26 15:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('emp', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('carNo', models.IntegerField()),
                ('RegNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('contactno', models.CharField(default='', max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('grantlevel', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servname', models.CharField(max_length=100)),
                ('servtype', models.CharField(max_length=100)),
                ('fees', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='loginDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loginName', models.CharField(max_length=100)),
                ('loginDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.owner')),
            ],
        ),
        migrations.CreateModel(
            name='CarService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.appointment')),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.service')),
            ],
        ),
        migrations.CreateModel(
            name='CarAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.appointment')),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.owner'),
        ),
    ]
