# Generated by Django 4.0 on 2022-01-26 16:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='EnginePower',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='EngineType',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fueltype',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.employee'),
        ),
    ]
